apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: voltron-quarkus-8f 
  janus-idp.io/tekton: voltron-quarkus-8f
  backstage.io/kubernetes-id: voltron-quarkus-8f
  backstage.io/kubernetes-namespace: rodan-demo 
  app.kubernetes.io/part-of: voltron-quarkus-8f
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml
