apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: voltron-quarkus-8f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: voltron-quarkus-8f 
  name: voltron-quarkus-8f
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: voltron-quarkus-8f 
